apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_USER: emFiYml4  # Base64 от "zabbix"
  POSTGRES_PASSWORD: emFiYml4cGFzc3dvcmQ=  # Base64 от "zabbixpassword"
  POSTGRES_DB: emFiYml4  # Base64 от "zabbix"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 2  # Для повышения отказоустойчивости
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:13
        envFrom:
        - secretRef:
            name: postgresql-secret
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgresql-data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - zabbix
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - zabbix
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: pvc-postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP


