apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-postgresql
  labels:
    app: postgresql
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Чтобы данные сохранялись при удалении PVC
  hostPath:
    path: "/mnt/data/postgresql"
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgresql
  labels:
    app: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
  volumeMode: Filesystem  # Указывает, что это файловая система (опция по умолчанию)
