apiVersion: v1
kind: Secret
metadata:
  name: zabbix-server-secret
type: Opaque
data:
  POSTGRES_USER: emFiYml4  # Base64 от "zabbix"
  POSTGRES_PASSWORD: emFiYml4cGFzc3dvcmQ=  # Base64 от "zabbixpassword"
  POSTGRES_DB: emFiYml4  # Base64 от "zabbix"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
        envFrom:
        - secretRef:
            name: zabbix-server-secret
        env:
        - name: DB_SERVER_HOST
          value: "postgresql" # Имя сервиса PostgreSQL
        ports:
        - containerPort: 10051
        readinessProbe:
          httpGet:
            path: /
            port: 10051
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 10051
          initialDelaySeconds: 30
          periodSeconds: 10
