apiVersion: v1
kind: Secret
metadata:
  name: zabbix-web-secret
type: Opaque
data:
  POSTGRES_USER: emFiYml4  # Base64 от "zabbix"
  POSTGRES_PASSWORD: emFiYml4cGFzc3dvcmQ=  # Base64 от "zabbixpassword"
  POSTGRES_DB: emFiYml4  # Base64 от "zabbix"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
        envFrom:
        - secretRef:
            name: zabbix-web-secret
        env:
        - name: DB_SERVER_HOST
          value: "postgresql" # Имя сервиса PostgreSQL
        - name: ZBX_SERVER_HOST
          value: "zabbix-server" # Имя сервиса Zabbix Server
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
